# Generated by Django 3.1.5 on 2022-11-10 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolstoreapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('dob', models.CharField(max_length=200, null=True)),
                ('gender', models.CharField(max_length=200, null=True)),
                ('no', models.CharField(max_length=200, null=True)),
                ('password', models.CharField(max_length=200, null=True)),
                ('password2', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='student',
        ),
    ]
