# Generated by Django 3.1.5 on 2022-11-10 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolstoreapp', '0003_auto_20221109_1931'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='username1',
            new_name='username',
        ),
    ]
